### ISSUE TITLE
Can i get the TDoA data in LPS?

### ISSUE THREAD

**Issue by Supredan** [bitcraze/lps-ros#11]
Hi,

I want to get the TDoA data in LPS(Loco position system),but unfortunately the output in the log_range is the data in the TWR mode, but in the LPS document,it is better to use the TDOA mode to fly multiple drones, so I want to know how to get the TDOA data in ros.

Thank!

**Comment by ataffanel** [comment]
I answered you on the forum, lets continue the discussion there: https://forum.bitcraze.io/viewtopic.php?f=3&t=3229&p=17816#p17780
