### ISSUE TITLE
Serial tests failed, cannot reliably get serial test information

### ISSUE THREAD

**Issue by pakrasi** [bitcraze/lps-ros#3]
I am trying to set up 6 anchors using the tutorial on your [wiki](https://wiki.bitcraze.io/doc:lps:index), and am facing the following issues - 
1. I cannot get the nodes to reliably communicate with picocom. When I connect to the node using the command `sudo picocom /dev/ttyACM0`, for some nodes, the terminal stops at `Terminal ready`, and does not output test information
2. For a couple of my nodes, the tests are failing, and I am getting the following in my terminal window - 

`TEST   : Initializing pressure sensor ... [FAIL] (32)`
`TEST   : Pressure sensor self-test ...`
`PRESS  : Self test pressure [FAIL]. low: 450, high: 1100, measured: 20`
`[FAIL]`
`TEST   : EEPROM self-test ... [OK]`
`TEST   : Initialize DWM1000 ... [OK]`
`TEST   : One or more self-tests failed, blocking startup!`

I have tried to reset the problematic nodes using the picocom, but it does not help. 

Thank you for your help. I look forward to get this up and running to work with the crazyflies!

**Comment by ataffanel** [comment]
This looks like hardware problem. On how many nodes do you get the problem and are all of them failing on the pressure sensor?
