### ISSUE TITLE
`log_range` callback raising out-of-range error

### ISSUE THREAD

**Issue by ghost** [bitcraze/lps-ros#4]
Hi!

I am testing the LPS with a single anchor from my desktop, to see if I can set up the communication correctly, and get reasonable range measurements.

When `roslaunch`ing the file `dwn_loc.launch`, after a few seconds I get this error.

```
[ERROR] [WallTime: 1475688260.689783] bad callback: <function callback at 0x7f949fe45f50>
Traceback (most recent call last):
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/adaldo/catkin_ws/src/lps-ros/scripts/log_range.py", line 15, in callback
    state = int(data.values[6])
IndexError: tuple index out of range
```

My `anchor_pos.yaml` is simply as follows.

```
n_anchors: 1
anchor0_pos: [0.0, 0.0, 0.0]
```

It loos like the callback is expecting `data.values` to contain 7 elements: the first six would be the actual measured ranges, and the 7-th would be some kind of flag.

I have tried to trick the code by changing my `anchor_pos.yaml` to the following.

```
n_anchors: 6
anchor0_pos: [0.0, 0.0, 0.0]
anchor1_pos: [0.0, 0.0, 0.0]
anchor2_pos: [0.0, 0.0, 0.0]
anchor3_pos: [0.0, 0.0, 0.0]
anchor4_pos: [0.0, 0.0, 0.0]
anchor5_pos: [0.0, 0.0, 0.0]
```

Do you know what is going wrong? Should I change the "6" in `data.values[6]` to something like `rospy.get_param(n_anchors)+1`?

Thanks for you help!

**Comment by ataffanel** [comment]
This piece of code is translating the log packet that comes from the Crazylie into a RangeArray topic. It expects the log packet to be defined that way: https://github.com/bitcraze/lps-ros/blob/master/launch/dwm_loc.launch#L18-L20. If you did not change the launch file it should not cause problems.

**Comment by ataffanel** [comment]
I am closing this issue since it should not be a problem if the log block are kept untouched. Feel free to open it again.
