### ISSUE TITLE
namespace problems with anchor position params

### ISSUE THREAD

**Issue by jolilj** [bitcraze/lps-ros#6]
Hi!
There seems to be a namespace problem with the loaded anchor position params. When launching dwm-loc.launch I get the following error:

`Traceback (most recent call last):
  File "**/catkin_ws/src/lps-ros/scripts/lps_viz.py", line 79, in <module>
    anchors_positions = get_anchors_pos()
  File **/catkin_ws/src/lps-ros/scripts/anchorpos.py", line 6, in get_anchors_pos
    n = rospy.get_param("n_anchors")
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/client.py", line 462, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: 'n_anchors'
Traceback (most recent call last):
  File **/catkin_ws/src/lps-ros/scripts/lps_pf.py", line 41, in <module>
    anchor_positions = get_anchors_pos()
  File "**/catkin_ws/src/lps-ros/scripts/anchorpos.py", line 6, in get_anchors_pos
    n = rospy.get_param("n_anchors")
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/client.py", line 462, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: 'n_anchors'
`

I played around a bit and added the yaml file loader line in the launch file within the new crazyflie group and then it worked.

All the best!

**Comment by ataffanel** [comment]
Hum, we have not used the particle filter for a while so you found a bug in its launchfile. Can you setup a pull-request for it so that we get it fix in master?

Thanks!
/Arnaud

**Comment by stephanbro** [comment]
@ataffanel I made some changes on the namespaces for all the launchfiles, so I'm not terribly surprised that something is a little funky.

It looks like this issue could potentially by solved by changing
`n = rospy.get_param("n_anchors")`
to
`n = rospy.get_param("/n_anchors")`

**Comment by ataffanel** [comment]
You might not be at the origin of this one @stephanbro, I have seen that before.

I guess what we need to decide is: is the anchor position better as a system constant or is there any use for an anchor position set per crazyflie. I cannot see any use for one position per crazyflie but it is more modular to allow it so I am not sure.
