### ISSUE TITLE
Crazyflie server-11 process has died error

### ISSUE THREAD

**Issue by KhristopherK** [bitcraze/lps-ros#8]
Hi, Ive been trying to run the demo on the lps-ros wiki site [https://wiki.bitcraze.io/doc:lps:ros](lps-ros wiki site) and during `roslaunch bitcraze_lps_estimator dwm_loc_ekf_hover.launch uri:=radio://0/80/250K x:=3 y:=2.3 z:=1.0` I get the following error, where rviz show no data incoming from the aircraft and the crazyflie server dying.

Does anyone know what I might be doing wrong? or any suggestions on how to fix this problem. Many thanks,

Khris
________________
Ros launch error below:

`khris@khris-XPS:~/catkin_ws$ roslaunch bitcraze_lps_estimator dwm_loc_ekf_hover.launch uri:=radio://0/80/1M x:=3 y:=2.3 z:=1.0
... logging to /home/khris/.ros/log/a8e093c0-de82-11e7-929c-9cb6d0e40021/roslaunch-khris-XPS-16274.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
started roslaunch server http://khris-XPS:37709/

SUMMARY
========

PARAMETERS
 * /crazyflie/anchor0_pos: [0.0, 3.9, 2.04]
 * /crazyflie/anchor1_pos: [3.6, 3.9, 2.04]
 * /crazyflie/anchor2_pos: [1.6, 0.6, 2.04]
 * /crazyflie/anchor3_pos: [0.0, 0.0, 0.0]
 * /crazyflie/anchor4_pos: [3.1, 0.0, 0.0]
 * /crazyflie/anchor5_pos: [1.6, 3.9, 0.0]
 * /crazyflie/crazyflie_add/genericLogTopicFrequencies: [30, 30, 30]
 * /crazyflie/crazyflie_add/genericLogTopic_log_kfpos_Variables: ['kalman.stateX',...
 * /crazyflie/crazyflie_add/genericLogTopic_log_kfqt_Variables: ['kalman.q0', 'ka...
 * /crazyflie/crazyflie_add/genericLogTopic_log_ranges_Variables: ['ranging.distanc...
 * /crazyflie/crazyflie_add/genericLogTopics: ['log_kfpos', 'lo...
 * /crazyflie/crazyflie_add/tf_prefix: crazyflie
 * /crazyflie/crazyflie_add/uri: radio://0/80/1M
 * /crazyflie/joy/dev: /dev/input/js0
 * /crazyflie/joystick_controller/use_crazyflie_controller: True
 * /crazyflie/n_anchors: 6
 * /crazyflie/pose/name: goal
 * /crazyflie/pose/rate: 30
 * /crazyflie/pose/x: 3
 * /crazyflie/pose/y: 2.3
 * /crazyflie/pose/z: 1.0
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /crazyflie/
    controller_bridge (bitcraze_lps_estimator/crazyflie_controller_bridge.py)
    crazyflie_add (crazyflie_driver/crazyflie_add)
    joy (joy/joy_node)
    joystick_controller (crazyflie_demo/controller.py)
    log_range (bitcraze_lps_estimator/log_range.py)
    lps_efk_bridge (bitcraze_lps_estimator/lps_ekf_bridge.py)
    lps_viz (bitcraze_lps_estimator/lps_viz.py)
    pose (crazyflie_demo/publish_pose_teleop.py)
  /
    crazyflie_server (crazyflie_driver/crazyflie_server)
    link1_broadcaster (tf/static_transform_publisher)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[rviz-1]: started with pid [16295]
process[crazyflie/crazyflie_add-2]: started with pid [16296]
process[crazyflie/joy-3]: started with pid [16297]
process[crazyflie/joystick_controller-4]: started with pid [16305]
process[crazyflie/controller_bridge-5]: started with pid [16319]
process[crazyflie/pose-6]: started with pid [16327]
[ INFO] [1513003870.079063774]: wait_for_service /add_crazyflie
[ INFO] [1513003870.080439826]: waitForService: Service [/add_crazyflie] has not been advertised, waiting...
process[crazyflie/lps_efk_bridge-7]: started with pid [16341]
/home/khris/catkin_ws/src/crazyflie_ros/crazyflie_demo/scripts/publish_pose_teleop.py:46: SyntaxWarning: name 'lastData' is assigned to before global declaration
  global lastData
process[crazyflie/lps_viz-8]: started with pid [16343]
process[crazyflie/log_range-9]: started with pid [16345]
process[link1_broadcaster-10]: started with pid [16346]
process[crazyflie_server-11]: started with pid [16348]
[ INFO] [1513003870.159782763]: waitForService: Service [/add_crazyflie] is now available.
[ INFO] [1513003870.159887606]: found /add_crazyflie
[ INFO] [1513003870.160082293]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
[ INFO] [1513003870.193810437]: Adding radio://0/80/1M as crazyflie with trim(0.000000, 0.000000). Logging: 1, Parameters: 1, Use ROS time: 1
[crazyflie/crazyflie_add-2] process has finished cleanly
log file: /home/khris/.ros/log/a8e093c0-de82-11e7-929c-9cb6d0e40021/crazyflie-crazyflie_add-2*.log
terminate called after throwing an instance of 'std::runtime_error'
  what():  timeout
**[crazyflie_server-11] process has died [pid 16348, exit code -6, cmd /home/khris/catkin_ws/devel/lib/crazyflie_driver/crazyflie_server __name:=crazyflie_server __log:=/home/khris/.ros/log/a8e093c0-de82-11e7-929c-9cb6d0e40021/crazyflie_server-11.log].**
log file: /home/khris/.ros/log/a8e093c0-de82-11e7-929c-9cb6d0e40021/crazyflie_server-11*.log
0x1d1d5a0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x124e7d0) ): Attempt to set a screen on a child window.
0x1d1d920 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x124e7d0) ): Attempt to set a screen on a child window.
0x1d25ee0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x124e7d0) ): Attempt to set a screen on a child window.
0x1d1ce80 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x124e7d0) ): Attempt to set a screen on a child window.
`

**Comment by ataffanel** [comment]
Hi,
What version of ROS and the crazyflie ros driver are you using?
