### ISSUE TITLE
dwa_loc_lms_hover.launch

### ISSUE THREAD

**Issue by rayaan92** [bitcraze/lps-ros#9]
Hi, 

I am battling to get the dwa_loc_lms_hover.launch file to work, has anyone gotten it to work and could you please guide me as to how you go it working.

Thank in advance,
Kind Regards,
Rayaan

**Comment by ataffanel** [comment]
Hi,
Can you maybe explain the problem you have more in details?
Also it would be useful to know what you are trying to do: this launch file is not supposed to be very useful anymore since there is a kalman filter estimator running in the Crazyflie.

**Comment by knmcguire** [comment]
closed to inactivity
